### PR TITLE
fix dlopen and improve init

### PR DESCRIPTION
**Pull request by benlorenz**
open libary with RTLD_GLOBAL to make symbols visible to julia
do initialization in __init__, print greeting and set application

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks.

**Comment by wbhart** [comment]
By the way, you mentioned that you set JULIA_CXX_RTTI. How did you do that precisely?

**Comment by benlorenz** [comment]
I was running julia with
`env JULIA_CXX_RTTI=1 julia`
as mentioned in [this Cxx.jl pull request](https://github.com/Keno/Cxx.jl/pull/313).

**Comment by wbhart** [comment]
Unfortunately, that doesn't work for me. But I'm glad it works for you.

I get an error:

error: run-time type information was disabled in PCH file but is currently
enabled
<built-in>:1:10: fatal error: 'Cxx.h' file not found
#include "Cxx.h"
         ^

I'll report it, but I'm not hopeful for a quick resolution.

**Comment by benlorenz** [comment]
Doing Pkg.build("Cxx") should fix this (contrary to what is written in the original pull request there).

**Comment by wbhart** [comment]
You mean, Pkg.build("Cxx") whilst running a Julia session with that
environment variable set?

**Comment by benlorenz** [comment]
Yes, each time you change that value you need to run Pkg.build before using Cxx, otherwise it wont load.
While trying this I noticed that it actually doesnt rebuild anything, it just seems to force the recompilation of some cached files when loading Cxx and doing
`$ touch ~/.julia/v0.6/Cxx/deps/path.jl`
instead of the pkg.build also seems to work.

```
$ env JULIA_CXX_RTTI=0 julia -e 'using Cxx; print("working\n")'
WARNING: <some warnings about header paths>
working
lorenz@eddie ~ $ touch .julia/v0.6/Cxx/deps/path.jl 
lorenz@eddie ~ $ env JULIA_CXX_RTTI=1 julia -e 'using Cxx; print("working\n")'
WARNING: <some warnings about header paths>
working
```

**Comment by wbhart** [comment]
Yes, that works for me. Thanks.

Any chance that some of the Clang warning messages can be fixed in the
relevant Polymake .h files?

**Pull request merged**
